### ISSUE TITLE
No default constructor found on class javax.xml.bind.JAXBElement - Need know why

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1012]
Hi,

I have generated Java code from XSD, using xjc tool, sheme is here : [http://dd.eionet.europa.eu/schemas/id2011850eu/AirQualityReporting.xsd](http://dd.eionet.europa.eu/schemas/id2011850eu/AirQualityReporting.xsd)

I can marshall XML from it, and its valid against XSD: [http://www.valachnet.cz/lvanek/0/CZ_E2a_hourly.xml](http://www.valachnet.cz/lvanek/0/CZ_E2a_hourly.xml)

While unmarshall back, I get exception:

com.sun.xml.bind.v2.ClassFactory create0
INFO: No default constructor found on class javax.xml.bind.JAXBElement
java.lang.NoSuchMethodException: javax.xml.bind.JAXBElement.<init>()
at java.lang.Class.getConstructor0(Unknown Source)
at java.lang.Class.getDeclaredConstructor(Unknown Source)
at com.sun.xml.bind.v2.ClassFactory.create0(ClassFactory.java:104)
at com.sun.xml.bind.v2.runtime.ClassBeanInfoImpl.createInstance(ClassBeanInfoImpl.java:286)

I discovered, that JAXB creates in method 'ClassBeanInfoImpl::createInstance'
jaxbType = javax.xml.bind.JAXBElement - But it's not have default constructor.

I need to know which XML fragment causes my problem, but NoSuchMethodException isn't informative.
It is possible surround calling: bean = ClassFactory.create0(jaxbType); in 'ClassBeanInfoImpl::createInstance' method with try/catch and throw more descriptive exception ?

Bye,
Lumir Vanek
#### Environment
Win 7 64b, JavaSE 7
#### Affected Versions
[2.2.7]

**Comment by winfriedgerlach** [comment]
@Tomas-Kraus @lukasj IMHO this is a support request that was resolved - could you please close this ticket?

**Comment by laurentschoelens** [comment]
@winfriedgerlach : issue closed
