### ISSUE TITLE
TR9401 catalog format support broken in JAXB 2.3.0?

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#1171]
Using XJC 2.3.0, passing a TR9401-format OASIS catalog file to the command-line via ```-catalog```, compilation errors out suggesting that only an XML catalog format is expected:

```
Exception in thread "main" javax.xml.catalog.CatalogException: JAXP09030002: Failed to parse the catalog file.
	at java.xml/javax.xml.catalog.CatalogMessages.reportRunTimeError(CatalogMessages.java:93)
	at java.xml/javax.xml.catalog.CatalogImpl.parse(CatalogImpl.java:297)
	at java.xml/javax.xml.catalog.CatalogImpl.load(CatalogImpl.java:171)
	at java.xml/javax.xml.catalog.CatalogManager.catalog(CatalogManager.java:73)
	at java.xml/javax.xml.catalog.CatalogManager.catalogResolver(CatalogManager.java:119)
	at com.sun.tools.xjc.CatalogUtil.getCatalog(CatalogUtil.java:65)
	at com.sun.tools.xjc.Options.addCatalog(Options.java:842)
	at com.sun.tools.xjc.Options.parseArgument(Options.java:691)
	at com.sun.tools.xjc.Driver$OptionsEx.parseArgument(Driver.java:532)
	at com.sun.tools.xjc.Options.parseArguments(Options.java:857)
	at com.sun.tools.xjc.Driver.run(Driver.java:261)
	at com.sun.tools.xjc.Driver.run(Driver.java:221)
	at com.sun.tools.xjc.Driver._main(Driver.java:144)
	at com.sun.tools.xjc.Driver.access$000(Driver.java:82)
	at com.sun.tools.xjc.Driver$1.run(Driver.java:103)
Caused by: org.xml.sax.SAXParseException; systemId: file:/Users/solind/Development/jOVAL/scap/schemas.cat; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:178)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:399)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:326)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1471)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:962)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:601)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:531)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:887)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:823)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:639)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:323)
	at java.xml/javax.xml.parsers.SAXParser.parse(SAXParser.java:275)
	at java.xml/javax.xml.catalog.CatalogImpl.parse(CatalogImpl.java:295)
	... 13 more
```

**Comment by danielkec** [comment]
Seems like new XML Catalogs(JEP 268) in java 9 don't support old TR9401 OASIS XML Catalog Format. Submitted JDK bug and waiting for confirmation

**Comment by lukasj** [comment]
Catalog files in OASIS TR9401-format are not supported by JAXB on JDK 9+. See  https://bugs.openjdk.java.net/browse/JDK-8231578
