### ISSUE TITLE
jaxb-xjc doesn't include runtime source files

### ISSUE THREAD

**Issue by bhleonard** [eclipse-ee4j/jaxb-ri#1287]
jaxb-xjc depends on the source files in its runtime directory, but doesn't include them in its jar, which causes schema generation to fail. The files exist in the 2.2.11 jar but not 2.3.0+. The maven plugin works because it includes them in its own jar.

com/sun/tools/xjc/runtime/
- JAXBContextFactory.java
- ZeroOneBooleanAdapter.java
- package-info.java

Running xjc with `com.sun.xml.tools.xjc.Driver` results in this exception:

`Exception in thread "main" java.lang.InternalError: Unable to load source code of com.sun.tools.xjc.runtime.ZeroOneBooleanAdapter as a resource
	at com.sun.codemodel.fmt.JStaticJavaFile$ResourceLoader.getResourceAsStream(JStaticJavaFile.java:234)
	at com.sun.codemodel.fmt.JStaticJavaFile.build(JStaticJavaFile.java:84)
	at com.sun.codemodel.JPackage.build(JPackage.java:446)
	at com.sun.codemodel.JCodeModel.build(JCodeModel.java:327)
	at com.sun.codemodel.JCodeModel.build(JCodeModel.java:317)
	at com.sun.tools.xjc.Driver.run(Driver.java:384)
	at com.sun.tools.xjc.Driver.run(Driver.java:191)
	at com.sun.tools.xjc.Driver._main(Driver.java:114)
	at com.sun.tools.xjc.Driver.access$000(Driver.java:52)
	at com.sun.tools.xjc.Driver$1.run(Driver.java:73)
`

Attached is a minimal maven project demonstrating the issue.

[xjc_issue.zip](https://github.com/eclipse-ee4j/jaxb-ri/files/2809776/xjc_issue.zip)

**Comment by ffang** [comment]
Hi @bravehorsie ,

Thanks for the fix.

May I ask when a new release containing this fix will be available?

Freeman

**Comment by bravehorsie** [comment]
@lukasj @m0mus Can you carry next release?

**Comment by ffang** [comment]
Any plan for the release guys?

Thanks!

**Comment by gicappa** [comment]
Eagerly waiting fro the release as well!
Thanks
