### ISSUE TITLE
xjc fails with open jdk 11 on windows

### ISSUE THREAD

**Issue by fithisux** [eclipse-ee4j/jaxb-ri#1292]
While OpenJDK8 xjc on my Windows 10 x64 works as expected on one of my xsds, it fails immediately on JDK11 with jaxb-ri xjc. The message is

> xjc simsphere_1_0.xsd
Java major version: 11
parsing a schema...
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make field public static final com.sun.tools.xjc.generator.bean.ImplStructureStrategy com.sun.tools.xjc.generator.bean.ImplStructureStrategy.INTF_AND_IMPL accessible: module com.sun.tools.xjc does not "exports com.sun.tools.xjc.generator.bean" to module com.sun.xml.bind
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:340)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:280)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:176)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:170)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.RuntimeEnumLeafInfoImpl.createEnumConstant(RuntimeEnumLeafInfoImpl.java:67)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.RuntimeEnumLeafInfoImpl.createEnumConstant(RuntimeEnumLeafInfoImpl.java:39)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.EnumLeafInfoImpl.calcConstants(EnumLeafInfoImpl.java:127)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.EnumLeafInfoImpl.getConstants(EnumLeafInfoImpl.java:181)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.EnumLeafInfoImpl.link(EnumLeafInfoImpl.java:188)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.ModelBuilder.link(ModelBuilder.java:427)
        at com.sun.xml.bind/com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:103)
        at com.sun.xml.bind/com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:439)
        at com.sun.xml.bind/com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
        at com.sun.xml.bind/com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
        at com.sun.xml.bind/com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
        at com.sun.xml.bind/com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
        at com.sun.xml.bind/com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:25)
        at java.xml.bind/javax.xml.bind.ContextFinder.find(ContextFinder.java:358)
        at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at java.xml.bind/javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:306)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationUnmarshaller(BindInfo.java:332)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl$1.<init>(AnnotationParserFactoryImpl.java:55)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl.create(AnnotationParserFactoryImpl.java:54)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.createAnnotationParser(NGCCRuntimeEx.java:371)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.annotation.action0(annotation.java:59)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.annotation.enterElement(annotation.java:84)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:287)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromEnterElement(NGCCHandler.java:121)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.foreignAttributes.enterElement(foreignAttributes.java:61)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:199)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:243)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:279)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:263)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:191)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:227)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.startElement(NGCCRuntime.java:233)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.tools.xjc/com.sun.tools.xjc.util.SubtreeCutter.startElement(SubtreeCutter.java:78)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement(ExtensionBindingChecker.java:120)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement(IncorrectNamespaceURIChecker.java:98)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement(CustomizationContextChecker.java:163)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader$SpeculationChecker.startElement(ModelLoader.java:414)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at com.sun.tools.xjc/com.sun.tools.xjc.reader.internalizer.VersionChecker.startElement(VersionChecker.java:73)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2708)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
        at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
        at com.sun.xml.xsom/com.sun.xml.xsom.parser.JAXPParser.parse(JAXPParser.java:70)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader$2.parse(ModelLoader.java:438)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:210)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:351)
        at com.sun.xml.xsom/com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:98)
        at com.sun.xml.xsom/com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:141)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader.createXSOMSpeculative(ModelLoader.java:455)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:310)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:121)
        at com.sun.tools.xjc/com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:76)
        at com.sun.tools.xjc/com.sun.tools.xjc.Driver.run(Driver.java:324)
        at com.sun.tools.xjc/com.sun.tools.xjc.Driver.run(Driver.java:191)
        at com.sun.tools.xjc/com.sun.tools.xjc.Driver._main(Driver.java:114)
        at com.sun.tools.xjc/com.sun.tools.xjc.Driver.access$000(Driver.java:52)
        at com.sun.tools.xjc/com.sun.tools.xjc.Driver$1.run(Driver.java:73)

**Comment by bravehorsie** [comment]
Can you please provide a minimal sample XSD that is failing?

**Comment by fithisux** [comment]
Yes : https://github.com/fithisux/DietSimsphere/blob/master/simsphere_xsds/simsphere_1_0.xsd

It fails with one of my project files.

**Comment by bravehorsie** [comment]
Related to [https://github.com/eclipse-ee4j/jaxb-api/issues/93](https://github.com/eclipse-ee4j/jaxb-api/issues/93)

**Comment by fithisux** [comment]
It is clear now. Thanks.

**Comment by gbburkhardt** [comment]
This change fixed a similar problem I was having.  Thanks.

**Comment by jhartotr** [comment]
Will be a new release build including this fix? Latest release seems to be https://github.com/eclipse-ee4j/jaxb-ri/releases/tag/2.3.2-RI and it was released before the fix.

**Comment by bravehorsie** [comment]
@jhartotr yes, next release should grab the fix.

**Comment by vedantx** [comment]
@bravehorsie Any workaround to use the standalone xjc tool before the release?
