### ISSUE TITLE
classpath error in xjc.bat - relaxngDatatype.jar not found

### ISSUE THREAD

**Issue by homebeaver** [eclipse-ee4j/jaxb-ri#1321]
Hi, 
I investigated the following problem running xjc on WIN10:
```
> xjc.bat -version
Java major version: 8
xjc 2.3.1
...
Java major version: 8
Ein Schema wird geparst ...
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/rngdatatype/ValidationContext
        at com.sun.xml.xsom.impl.parser.ParserContext.newNGCCRuntime(ParserContext.java:154)
        at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:128)
        at com.sun.xml.xsom.impl.parser.ParserContext.<init>(ParserContext.java:104)
        at com.sun.xml.xsom.parser.XSOMParser.<init>(XSOMParser.java:113)
        at com.sun.tools.xjc.ModelLoader.createXSOMParser(ModelLoader.java:408)
        at com.sun.tools.xjc.ModelLoader.createXSOMSpeculative(ModelLoader.java:481)
        at com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:340)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:151)
        at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:106)
        at com.sun.tools.xjc.Driver.run(Driver.java:354)
        at com.sun.tools.xjc.Driver.run(Driver.java:221)
        at com.sun.tools.xjc.Driver._main(Driver.java:144)
        at com.sun.tools.xjc.Driver.access$000(Driver.java:82)
        at com.sun.tools.xjc.Driver$1.run(Driver.java:103)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.rngdatatype.ValidationContext
        at com.sun.istack.tools.ParallelWorldClassLoader.findClass(ParallelWorldClassLoader.java:127)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
```
I found 

`set JAXB_PATH=%JAXB_HOME%/mod/jaxb-xjc.jar;...;%JAXB_HOME%/lib/relaxngDatatype.jar`

**/lib/** does not exists! Should it be `.../mod/relaxng-datatype.jar` ?

regards

**Comment by homebeaver** [comment]
some rows above, another **lib**:

`if exist "%JAXB_HOME%\lib\jaxb-xjc.jar" goto CHECKJAVAHOME`

**Comment by homebeaver** [comment]
Hi, I notice that @lukasj has fixed this problem on 2 Jan

commit https://github.com/eclipse-ee4j/jaxb-ri/commit/d64d08da5c301bf8ffb40c7857095a9b986c217b

tkx

**Comment by fwindolf** [comment]
I was still having the error with 2.3.1 downloaded from https://javaee.github.io/jaxb-v2/.

Fixed with changing the env variable definition to 
```
set JAXB_PATH=%JAXB_HOME%/mod/jaxb-xjc.jar;%JAXB_HOME%/mod/jaxb-api.jar;%JAXB_HOME%/mod/codemodel.jar;%JAXB_HOME%/mod/jaxb-runtime.jar;%JAXB_HOME%/mod/istack-commons-runtime.jar;%JAXB_HOME%/mod/istack-commons-tools.jar;%JAXB_HOME%/mod/rngom.jar;%JAXB_HOME%/mod/xsom.jar;%JAXB_HOME%/mod/dtd-parser.jar;%JAXB_HOME%/mod/txw2.jar;%JAXB_HOME%/mod/stax-ex.jar;%JAXB_HOME%/mod/FastInfoset.jar;%JAXB_HOME%/mod/javax.activation-api.jar;%JAXB_HOME%/mod/relaxng-datatype.jar
```

**Comment by trensetim** [comment]
solution provided by @fwindolf  fixed it for me too. One could consider patching xjc?

**Comment by usontakke-processia** [comment]
Thanks @fwindolf
