### ISSUE TITLE
Published 2.3.2 txw2 jar is not an osgi bundle

### ISSUE THREAD

**Issue by malm66** [eclipse-ee4j/jaxb-ri#1435]
I am trying to put together an OSGI compatible jaxb runtime for our project. One stumbling block is the published twx2 jar which seems to be missing the relevant Bundle-... and Export-Package entries in its manifest. Therefore when the platform is resolving the bundle dependencies it complains that policy.jar has unsatisfied import requirements:

org.osgi.framework.BundleException: Could not resolve module: com.sun.xml.ws.policy [440]
  Unresolved requirement: Import-Package: com.sun.xml.txw2; version="[2.3.0,3.0.0)"

**Comment by lukasj** [comment]
should be fixed in [2.3.3](https://www.eclipse.org/lists/jaxb-impl-dev/msg00012.html), feel, free to reopen if not

**Comment by malm66** [comment]
Thanks Lukas, will there be a 2.3.3 release of the jaxws-rt as well soon? Because jaxws-rt 2.3.2 relies on jaxb-runtime which in turn drags in the defective twx2.

**Comment by lukasj** [comment]
yeah, if some would have listened to me in the past....

to make the story short jaxb 2.3.3 is packaged the same way 2.2.x versions used to be with addition of OSGi headers to "old" bundles coming from 'com.sun.xml.bind' group id. So you should be able to use [jaxb-impl](https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3/jaxb-impl-2.3.3.jar) for now. It is also the jar, jaxws-rt 2.3.3 depends on once it becomes available ([this](https://bugs.eclipse.org/bugs/show_bug.cgi?id=561497) has to be fixed first) and the only option to use should you need to make it work also on JDK11+

**Comment by lukasj** [comment]
...in the worst case, there also exists jaxb-osgi.jar containing everything

**Comment by malm66** [comment]
As we do need Java 11 support but have a little bit of time until our production release can I use jaxws-rt 2.3.3-b01 for the time being or is that known to have serious flaws?

**Comment by lukasj** [comment]
I'd rather wait that day or two, esp if osgi is what you do care about OSGi - ie [this](https://github.com/eclipse-ee4j/metro-jax-ws/commit/6fbc97ee4c0cdd8869db0d6a8fd25dbb10a792dd) may hit you with 2.3.3-b01 (but there were not so many [changes](https://github.com/eclipse-ee4j/metro-jax-ws/compare/2.3.3-b01...2.3.3))

**Comment by malm66** [comment]
Hi Lukas, this is a continuation of yesterday's conversation and if this is the wrong place happy to post this somewhere else.

I tried, against your advice, jaxws-rt 2.3.3-b01 and ran into multiple issues:

1. the currently published gambal 4.0.1 jar is not an OSGI bundle
2. there is a dependency on woodstock-core 5.3.0 not listed in mvnrepository
3. there is a dependency on jakarta.jws-api 1.1.1 which is not listed in mvnrepository and is outdated. jaxws-rt 2.3.2 depends on jakarta.jws-api 2.1.0
4. I suspect it also depends on one or more of the following but they are not listed  in mvnrepository:
-> jakarta.activation-api 1.22
-> jakarta.annotation-api 1.3.5
-> jakarta.xml.bind-api 2.3.2
-> jakarta.xml.soap-api 1.4.2
-> jakarta.xml.ws-api 2.3.3
5. the dependency on ha-api is a problem as ha-api depends on hk2. In mvnrepository this is listed as optional but in the manifest it is mandatory

**Comment by lukasj** [comment]
well, mvnrepository is *wrong place* to look, maven central is what matters and ie https://repo1.maven.org/maven2/jakarta/annotation/jakarta.annotation-api/ shows v 1.3.5 which mvnrepository is saying does not exists

wrt jws-api version - technically they are the same, the only difference is version number
wrt ha-api and gmbal I have no control over these two but both are mandatory for jaxws runtime to work properly

**Comment by lukasj** [comment]
hmm, jakarta.xml.bind-api 2.3.2 must be 2.3.3

**Comment by malm66** [comment]
Just FYI: The gmbal manifest issue is known: [https://github.com/eclipse-ee4j/orb-gmbal/issues/21](https://github.com/eclipse-ee4j/orb-gmbal/issues/21)

**Comment by lukasj** [comment]
from jaxws point of view, https://github.com/eclipse-ee4j/orb-gmbal/pull/20 is quite important too

**Comment by malm66** [comment]
I am slowly making progress with my OSGI / Java 11 / JAXWS quest. At least no more obvious missing dependencies and the code is actually runnable. I am now getting a "missing annotation" exception although the annotation is certainly on the mentioned class. I suspect there is still one bundle or more bundles missing. So which bundle does the webservices annotation processing?

`
com.sun.xml.ws.model.RuntimeModelerException: A WebService annotation is not present on class: au.net.synergy.wts.server.ws.client.management.ServerManager
	at com.sun.xml.ws.model.RuntimeModeler.buildRuntimeModel(RuntimeModeler.java:239)
	at com.sun.xml.ws.db.DatabindingImpl.<init>(DatabindingImpl.java:70)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:44)
	at com.sun.xml.ws.db.DatabindingProviderImpl.create(DatabindingProviderImpl.java:28)
	at com.sun.xml.ws.db.DatabindingFactoryImpl.createRuntime(DatabindingFactoryImpl.java:90)
	at com.sun.xml.ws.client.WSServiceDelegate.buildRuntimeModel(WSServiceDelegate.java:852)
	at com.sun.xml.ws.client.WSServiceDelegate.createSEIPortInfo(WSServiceDelegate.java:869)
	at com.sun.xml.ws.client.WSServiceDelegate.addSEI(WSServiceDelegate.java:832)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:421)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:390)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:372)
	at javax.xml.ws.Service.getPort(Service.java:139)
	at au.net.synergy.wts.server.ws.client.management.ServerManagerImplService.getServerManagerImplPort(ServerManagerImplService.java:56)
`

**Comment by malm66** [comment]
After upgrading to jaxws-rt.2.3.3 I am getting the following error, any ideas what's wrong?
`
java.lang.InternalError: MASM0010: Unable to unmarshall metro config file from location [ bundleresource://1110.fwk401022084/META-INF/jaxws-tubes-default.xml ]
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:234)
	at com.sun.xml.ws.assembler.MetroConfigLoader.init(MetroConfigLoader.java:117)
	at com.sun.xml.ws.assembler.MetroConfigLoader.<init>(MetroConfigLoader.java:91)
	at com.sun.xml.ws.assembler.TubelineAssemblyController.getTubeCreators(TubelineAssemblyController.java:64)
	at com.sun.xml.ws.assembler.MetroTubelineAssembler.createClient(MetroTubelineAssembler.java:90)
	at com.sun.xml.ws.client.Stub.createPipeline(Stub.java:313)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:280)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:213)
	at com.sun.xml.ws.client.Stub.<init>(Stub.java:228)
	at com.sun.xml.ws.client.sei.SEIStub.<init>(SEIStub.java:68)
	at com.sun.xml.ws.client.WSServiceDelegate.getStubHandler(WSServiceDelegate.java:791)
	at com.sun.xml.ws.client.WSServiceDelegate.createEndpointIFBaseProxy(WSServiceDelegate.java:780)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:422)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:390)
	at com.sun.xml.ws.client.WSServiceDelegate.getPort(WSServiceDelegate.java:372)
	at javax.xml.ws.Service.getPort(Service.java:139)
	at au.net.synergy.wts.server.ws.client.management.ServerManagerImplService.getServerManagerImplPort(ServerManagerImplService.java:56)
	at au.net.synergy.wts.server.ws.client.management.helper.PortFactory.getPort(PortFactory.java:31)
	at .......
Caused by: javax.xml.bind.JAXBException: "com.sun.xml.ws.runtime.config" doesnt contain ObjectFactory.class or jaxb.index
	at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:260)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:171)
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:313)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:478)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:435)
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:336)
	at com.sun.xml.ws.assembler.MetroConfigLoader.createJAXBContext(MetroConfigLoader.java:268)
	at com.sun.xml.ws.assembler.MetroConfigLoader.loadMetroConfig(MetroConfigLoader.java:226)
	... 81 more

`
