### ISSUE TITLE
xjc: Option to generate old package names

### ISSUE THREAD

**Issue by cwalther** [eclipse-ee4j/jaxb-ri#1475]
Feature request: Since version 3.0, xjc generates Java code containing new package names like

```java
import jakarta.xml.bind.annotation.XmlType;
import org.glassfish.jaxb.core.Locatable;
```

It should have an option to instead generate the same old package names as 2.3 and earlier did:

```java
import javax.xml.bind.annotation.XmlType;
import com.sun.xml.bind.Locatable;
```

Perhaps coupled to the `-target 2.3` (or lower) command line option, or with a separate option.

Rationale: We have a legacy codebase that still uses the `javax` packages, with code originally generated by xjc 2.x. When regenerating that code due to schema updates, it would be nice to be able to use modern tools and take advantage of any advancements in them. At some point, the old tools won’t even run on current developer machines anymore (like currently due to bug #1474).

**Comment by lukasj** [comment]
`-target 2.3` can be used to have `javax.xml.bind` instead of `jakarta.xml.bind` in xjc generated sources

**Comment by cwalther** [comment]
I finally got around to testing this, and I am having mixed success with jaxb-ri-3.0.1-20210323.002252-12.

It works on some schemas, and the output is mostly identical to what I got with 2.2/2.3. On others however, it fails with

```
cwalther@cwubu64p:schemas$ jaxb-ri-3.0.1-20210323.002252-12/bin/xjc.sh -target 2.3 -d ../generated -no-header -Xlocator package.xsd idevproject.xsd
Java major version: 11
Mar 23, 2021 2:15:01 PM com.sun.tools.xjc.Options addClassNameReplacers
WARNING: Jakarta does not support version 2.x version 
parsing a schema...
Exception in thread "main" java.lang.AssertionError: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory]
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:326)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationUnmarshaller(BindInfo.java:332)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl$1.<init>(AnnotationParserFactoryImpl.java:55)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl.create(AnnotationParserFactoryImpl.java:54)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.createAnnotationParser(NGCCRuntimeEx.java:371)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.annotation.action0(annotation.java:59)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.annotation.enterElement(annotation.java:84)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:287)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromEnterElement(NGCCHandler.java:121)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.foreignAttributes.enterElement(foreignAttributes.java:61)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:199)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:243)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:279)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:263)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:191)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:227)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.startElement(NGCCRuntime.java:233)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.util.SubtreeCutter.startElement(SubtreeCutter.java:78)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement(ExtensionBindingChecker.java:120)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement(IncorrectNamespaceURIChecker.java:98)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement(CustomizationContextChecker.java:163)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader$SpeculationChecker.startElement(ModelLoader.java:414)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.internalizer.VersionChecker.startElement(VersionChecker.java:73)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:551)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:510)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2710)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.parser.JAXPParser.parse(JAXPParser.java:70)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader$2.parse(ModelLoader.java:438)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:210)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:351)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.includeSchema(NGCCRuntimeEx.java:244)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.includeDecl.action0(includeDecl.java:53)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.includeDecl.leaveElement(includeDecl.java:120)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.state.NGCCRuntime.endElement(NGCCRuntime.java:289)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.util.SubtreeCutter.endElement(SubtreeCutter.java:82)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.endElement(CustomizationContextChecker.java:169)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.endElement(XMLFilterImpl.java:570)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:610)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1718)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2883)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:534)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:888)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1216)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:635)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.parse(XMLFilterImpl.java:357)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.parser.JAXPParser.parse(JAXPParser.java:70)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader$2.parse(ModelLoader.java:438)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:210)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:351)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:98)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:141)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader.createXSOMSpeculative(ModelLoader.java:455)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader.loadXMLSchema(ModelLoader.java:310)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:121)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:76)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.Driver.run(Driver.java:329)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.Driver.run(Driver.java:192)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.Driver._main(Driver.java:115)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.Driver.access$000(Driver.java:53)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.Driver$1.run(Driver.java:74)
Caused by: jakarta.xml.bind.JAXBException: Implementation of Jakarta XML Binding-API has not been found on module path or classpath.
 - with linked exception:
[java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory]
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:255)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:243)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.find(ContextFinder.java:407)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at com.sun.tools.xjc@3.0.1-SNAPSHOT/com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:306)
	... 93 more
Caused by: java.lang.ClassNotFoundException: org.glassfish.jaxb.runtime.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:92)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:125)
	at jakarta.xml.bind@3.0.1/jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:253)
	... 98 more
```

This is with the stock OpenJDK 11.0.10 of Ubuntu 20.04.

I think I’ve narrowed it down to the presence of `<xsd:annotation>` in the schema: when I comment out all of those, it runs successfully (but of course produces garbage, because the annotations were important).

**Comment by cwalther** [comment]
Okay, the failure is not related to `-target 2.3`, it also occurs with just `xjc.sh -d out test.xsd` with a schema as simple as
```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema">
<annotation/>
</schema>
```
`git bisect` indicates that 9de1e0aabe19e17180fe91eba3f13217dbcc947a broke it. I’ll leave the rest to you.

**Comment by lukasj** [comment]
@cwalther try again :-) fixed by 3f89c1b (if you don't want to wait an hour or so for nightly, add `--add-modules com.sun.xml.bind` to `xjc` on line 85). Thanks for heads-up!

**Comment by cwalther** [comment]
However, still no dice with the commit before that – now it just ignores the `<xsd:annotation>`s, or possibly the `<jxb:…>` within them. Another `git bisect` says 36aded3fbb846c9518ed386f97e8cad0db39401f broke that. From a quick glance over that commit – does that mean it can no longer compile schemas that have `xmlns:jxb="http://java.sun.com/xml/ns/jaxb"` instead of the new `xmlns:jxb="https://jakarta.ee/xml/ns/jaxb"`?

**Comment by cwalther** [comment]
Yup, the `--add-modules` fixes the exception. Thanks!

That still leaves the namespace problem though – xjc 3.0 becomes a lot less useful if it can’t read my old schemas anymore. I could probably update them, but would need to check first if all build environments support it.

**Comment by lukasj** [comment]
let me try to take a look at that if I can come up with solution for it within 3.0.1. I think I still have a week or for two for that (but also bunch of other stuff to do :-/, thus no promise)

**Comment by cwalther** [comment]
That would be great, but no pressure. For now I’m happy with the 2.3.4 update.

And when I update my schemas to the new namespace and version=3.0, the output looks good. A few minor reordered lines, but as long as the new ordering stays consistent, there’s no problem with that.

**Comment by lukasj** [comment]
I'm going to backport #1519 to 2.3.4 before it gets published as well as other most recent fixes from master (mostly fixes related to JDK 11, there ~4 I think)

**Comment by cwalther** [comment]
Ah, cool. That was indeed one of the things I saw reordered. The others were imports.

**Comment by patric-r** [comment]
@lukasj Any ETA for final 2.3.4?

**Comment by patric-r** [comment]
@lukasj Any updates regarding 2.3.4?

**Comment by lukasj** [comment]
it's out already

**Comment by patric-r** [comment]
@lukasj Thanks - I've seen it in maven central but because it's missing in the github releases I was unsure if it is final.

**Comment by lukasj** [comment]
once it is in central, it cannot be changed. Corresponding GH release is just a cherry on the cake (even though important) - it will be done as I go through all projects which were released recently
