### ISSUE TITLE
JCommentPart#escape(String) may fail with StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by schwitzkroko** [eclipse-ee4j/jaxb-ri#1480]
When we xjc-generate java code based on a xsd we encounter a case where text content of a 'xs:documentation' element ends with an asterisk char. A StringIndexOutOfBoundsException makes the execution fail.

From checking the JCommentPart#escape(String) code i assume the expectation here is, that such an occurance is always terminated with a slash (javadoc-like?). 
I don´t think this expectation can always be met. I suggest that a check on the string length is introduced before trying 's.charAt(i+1)'.

```
...
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:109)
... 40 more
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 717
at java.lang.String.charAt(String.java:658)
at com.sun.codemodel.JCommentPart.escape(JCommentPart.java:133)
at com.sun.codemodel.JCommentPart.format(JCommentPart.java:95)
at com.sun.codemodel.JDocComment.generate(JDocComment.java:150)
at com.sun.codemodel.JFormatter.g(JFormatter.java:320)
at com.sun.codemodel.JEnumConstant.declare(JEnumConstant.java:134)
at com.sun.codemodel.JFormatter.d(JFormatter.java:346)
at com.sun.codemodel.JDefinedClass.declareBody(JDefinedClass.java:787)
at com.sun.codemodel.JDefinedClass.declare(JDefinedClass.java:774)
at com.sun.codemodel.JFormatter.d(JFormatter.java:346)
at com.sun.codemodel.JFormatter.write(JFormatter.java:420)
at com.sun.codemodel.JPackage.build(JPackage.java:422)
at com.sun.codemodel.JCodeModel.build(JCodeModel.java:328)
at com.sun.codemodel.JCodeModel.build(JCodeModel.java:318)
at com.sun.tools.xjc.XJCBase._doXJC(XJCBase.java:817)
at com.sun.tools.xjc.XJCBase.doXJC(XJCBase.java:755)
at com.sun.tools.xjc.XJCBase.execute(XJCBase.java:654)
at com.sun.tools.xjc.XJC2Task.execute(XJC2Task.java:25)
at org.jvnet.jaxb2_commons.xjc.XJC2Task.execute(XJC2Task.java:35)
at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:293)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
...
```

the behavior was observed with  'org.glassfish.jaxb:codemodel:2.3.3' used by the current jxb-xjc version 2.3.3 . it is published since 2019-10-15 version '2.3.3-b01'. 
The commit we see for that is 83c5858de344a426724749e3756785a63caa02b2 .

**Comment by Cagrosso** [comment]
@lukasj I am also running into this issue with some xsd files that I am trying to parse.  Is there a release planned that includes the fix for this issue? 

Thanks for fixing it!

**Comment by lukasj** [comment]
if it goes well, later this week; if it goes wrong, by beginning of Dec. So to be safe, count with something in between and be surprised should it show up sooner ;-)
