### ISSUE TITLE
Injector checks for sun.misc.unsafe, but still fails

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jaxb-ri#1529]
`META-INF.versions.9.org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector` contains this:

```
 try {
                U = AccessController.doPrivileged(new PrivilegedExceptionAction() {
                    @Override
                    public Object run() throws Exception {
                        Class u = classForNames("sun.misc.Unsafe", "jdk.internal.misc.Unsafe");
                        Field theUnsafe = u.getDeclaredField("theUnsafe");
                        theUnsafe.setAccessible(true);
                        return theUnsafe.get(null);
                    }
                });
                defineClass = AccessController.doPrivileged(new PrivilegedExceptionAction<Method>() {
                    @Override
                    public Method run() throws Exception {
                        try {
                            return U.getClass().getMethod("defineClass",
                                    new Class[]{String.class,
                                        byte[].class,
                                        Integer.TYPE,
                                        Integer.TYPE,
                                        ClassLoader.class,
                                        ProtectionDomain.class});
                        } catch (NoSuchMethodException | SecurityException ex) {
                            throw ex;
                        }
                    }
                });
            } catch (SecurityException | PrivilegedActionException ex) {
                Logger.getLogger(Injector.class.getName()).log(Level.SEVERE, null, ex);
            }
```

It checks for "sun.misc.Unsafe", which passes, but then when it tries to get to the `defineClass` method it fails using JDK 16:

```
Apr 06, 2021 2:51:37 AM org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector <clinit>
SEVERE: null
java.security.PrivilegedActionException: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:558)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector.<clinit>(Injector.java:161)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.AccessorInjector.prepare(AccessorInjector.java:51)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.OptimizedAccessorFactory.get(OptimizedAccessorFactory.java:157)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.Accessor$FieldReflection.optimize(Accessor.java:249)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.<init>(TransducedAccessor.java:205)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.TransducedAccessor.get(TransducedAccessor.java:145)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.calcTransducer(RuntimeClassInfoImpl.java:213)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.getTransducer(RuntimeClassInfoImpl.java:187)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.createTransducer(RuntimeModelBuilder.java:108)
	at org.glassfish.jaxb.runtime.v2.model.impl.SingleTypePropertyInfoImpl.getTransducer(SingleTypePropertyInfoImpl.java:109)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeAttributePropertyInfoImpl.link(RuntimeAttributePropertyInfoImpl.java:49)
	at org.glassfish.jaxb.runtime.v2.model.impl.ClassInfoImpl.link(ClassInfoImpl.java:1201)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeClassInfoImpl.link(RuntimeClassInfoImpl.java:165)
	at org.glassfish.jaxb.runtime.v2.model.impl.ModelBuilder.link(ModelBuilder.java:411)
	at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeModelBuilder.link(RuntimeModelBuilder.java:96)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:417)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:251)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:77)
	at org.glassfish.jaxb.runtime.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1111)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:140)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:274)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:263)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:390)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationContext(BindInfo.java:306)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getCustomizationUnmarshaller(BindInfo.java:332)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl$1.<init>(AnnotationParserFactoryImpl.java:55)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.AnnotationParserFactoryImpl.create(AnnotationParserFactoryImpl.java:54)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.createAnnotationParser(NGCCRuntimeEx.java:371)
	at com.sun.xml.xsom.impl.parser.state.annotation.action0(annotation.java:59)
	at com.sun.xml.xsom.impl.parser.state.annotation.enterElement(annotation.java:84)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:287)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.revertToParentFromEnterElement(NGCCHandler.java:121)
	at com.sun.xml.xsom.impl.parser.state.foreignAttributes.enterElement(foreignAttributes.java:61)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.NGCCHandler.spawnChildFromEnterElement(NGCCHandler.java:84)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:199)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:243)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:279)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:263)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:191)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.sendEnterElement(NGCCRuntime.java:392)
	at com.sun.xml.xsom.impl.parser.state.Schema.enterElement(Schema.java:227)
	at com.sun.xml.xsom.impl.parser.state.NGCCRuntime.startElement(NGCCRuntime.java:233)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
	at com.sun.tools.xjc.util.SubtreeCutter.startElement(SubtreeCutter.java:78)
	at com.sun.tools.xjc.reader.ExtensionBindingChecker.startElement(ExtensionBindingChecker.java:120)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
	at com.sun.tools.xjc.reader.xmlschema.parser.IncorrectNamespaceURIChecker.startElement(IncorrectNamespaceURIChecker.java:98)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
	at com.sun.tools.xjc.reader.xmlschema.parser.CustomizationContextChecker.startElement(CustomizationContextChecker.java:163)
	at java.xml/org.xml.sax.helpers.XMLFilterImpl.startElement(XMLFilterImpl.java:539)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner$LocationResolver.startElement(DOMForestScanner.java:117)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit(DOMScanner.java:214)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit(DOMScanner.java:251)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.visit(DOMScanner.java:220)
	at org.glassfish.jaxb.core.unmarshaller.DOMScanner.scan(DOMScanner.java:97)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:62)
	at com.sun.tools.xjc.reader.internalizer.DOMForestScanner.scan(DOMForestScanner.java:70)
	at com.sun.tools.xjc.reader.internalizer.DOMForestParser.parse(DOMForestParser.java:74)
	at com.sun.tools.xjc.ModelLoader$XMLSchemaParser.parse(ModelLoader.java:210)
	at com.sun.xml.xsom.impl.parser.NGCCRuntimeEx.parseEntity(NGCCRuntimeEx.java:351)
	at com.sun.xml.xsom.impl.parser.ParserContext.parse(ParserContext.java:98)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:141)
	at com.sun.xml.xsom.parser.XSOMParser.parse(XSOMParser.java:130)
	at com.sun.tools.xjc.ModelLoader.createXSOM(ModelLoader.java:475)
	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:240)
	at com.sun.tools.xjc.api.impl.s2j.SchemaCompilerImpl.bind(SchemaCompilerImpl.java:67)
	at com.sun.tools.ws.processor.modeler.wsdl.JAXBModelBuilder.bind(JAXBModelBuilder.java:112)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.buildJAXBModel(WSDLModeler.java:2268)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.internalBuildModel(WSDLModeler.java:168)
	at com.sun.tools.ws.processor.modeler.wsdl.WSDLModeler.buildModel(WSDLModeler.java:111)
	at com.sun.tools.ws.wscompile.WsimportTool.buildWsdlModel(WsimportTool.java:414)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:175)
	at com.sun.tools.ws.wscompile.WsimportTool.run(WsimportTool.java:153)
	at com.sun.tools.ws.ant.WsImportBase.runInVm(WsImportBase.java:569)
	at com.sun.tools.ws.ant.WsTask2.execute(WsTask2.java:457)
	at com.sun.tools.ws.ant.WsImportBase.execute(WsImportBase.java:552)
	at com.sun.tools.ws.ant.WsImport2.execute(WsImport2.java:23)
	at com.sun.istack.tools.ProtectedTask.execute(ProtectedTask.java:67)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.CallTarget.execute(CallTarget.java:105)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at jdk.internal.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.taskdefs.Sequential.execute(Sequential.java:68)
	at net.sf.antcontrib.logic.IfTask.execute(IfTask.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.TaskAdapter.execute(TaskAdapter.java:154)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.maven.plugin.antrun.AntRunMojo.execute(AntRunMojo.java:313)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.lang.NoSuchMethodException: sun.misc.Unsafe.defineClass(java.lang.String,[B,int,int,java.lang.ClassLoader,java.security.ProtectionDomain)
	at java.base/java.lang.Class.getMethod(Class.java:2195)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector$3.run(Injector.java:165)
	at org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector$3.run(Injector.java:161)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:554)
	... 178 more
```

**Comment by lukasj** [comment]
`ljungman-mac:repository lukas$ javap -v jar:file:///Users/lukas/.m2/repository/com/sun/xml/bind/jaxb-osgi/3.0.1/jaxb-osgi-3.0.1.jar\!/META-INF/versions/9/org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector.class
Classfile jar:file:///Users/lukas/.m2/repository/com/sun/xml/bind/jaxb-osgi/3.0.1/jaxb-osgi-3.0.1.jar!/META-INF/versions/9/org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector.class` says you are not right:

```
  Last modified Apr 4, 2021; size 716 bytes
  MD5 checksum 81f87b2259381538d4a1cc4f8cfc4b14
  Compiled from "Injector.java"
final class org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector
  minor version: 0
  major version: 53
  flags: (0x0030) ACC_FINAL, ACC_SUPER
  this_class: #2                          // org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector
  super_class: #3                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 3, attributes: 1
Constant pool:
   #1 = Methodref          #3.#23         // java/lang/Object."<init>":()V
   #2 = Class              #24            // org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector
   #3 = Class              #25            // java/lang/Object
   #4 = Utf8               <init>
   #5 = Utf8               ()V
   #6 = Utf8               Code
   #7 = Utf8               LineNumberTable
   #8 = Utf8               LocalVariableTable
   #9 = Utf8               this
  #10 = Utf8               Lorg/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector;
  #11 = Utf8               inject
  #12 = Utf8               (Ljava/lang/ClassLoader;Ljava/lang/String;[B)Ljava/lang/Class;
  #13 = Utf8               cl
  #14 = Utf8               Ljava/lang/ClassLoader;
  #15 = Utf8               className
  #16 = Utf8               Ljava/lang/String;
  #17 = Utf8               image
  #18 = Utf8               [B
  #19 = Utf8               find
  #20 = Utf8               (Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/Class;
  #21 = Utf8               SourceFile
  #22 = Utf8               Injector.java
  #23 = NameAndType        #4:#5          // "<init>":()V
  #24 = Utf8               org/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector
  #25 = Utf8               java/lang/Object
{
  org.glassfish.jaxb.runtime.v2.runtime.reflect.opt.Injector();
    descriptor: ()V
    flags: (0x0000)
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 18: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Lorg/glassfish/jaxb/runtime/v2/runtime/reflect/opt/Injector;

  static java.lang.Class inject(java.lang.ClassLoader, java.lang.String, byte[]);
    descriptor: (Ljava/lang/ClassLoader;Ljava/lang/String;[B)Ljava/lang/Class;
    flags: (0x0008) ACC_STATIC
    Code:
      stack=1, locals=3, args_size=3
         0: aconst_null
         1: areturn
      LineNumberTable:
        line 27: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       2     0    cl   Ljava/lang/ClassLoader;
            0       2     1 className   Ljava/lang/String;
            0       2     2 image   [B

  static java.lang.Class find(java.lang.ClassLoader, java.lang.String);
    descriptor: (Ljava/lang/ClassLoader;Ljava/lang/String;)Ljava/lang/Class;
    flags: (0x0008) ACC_STATIC
    Code:
      stack=1, locals=2, args_size=2
         0: aconst_null
         1: areturn
      LineNumberTable:
        line 34: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       2     0    cl   Ljava/lang/ClassLoader;
            0       2     1 className   Ljava/lang/String;
}
SourceFile: "Injector.java"
```

What am I doing wrong?

**Comment by arjantijms** [comment]
> What am I doing wrong?

I checked the jar file with as well. It seems like the class is there allright.

Still, both a tool (I used Eclipse) and actual execution choose the non-JDK9+ file. Puzzling...

**Comment by arjantijms** [comment]
On my system macOS 11.2.3 with Zulu JDK 16, at least a completely standalone test works:

```java
public class TestJaxbMr {
    
    public static void main(String[] args) {
        Unmarshaller u = BindInfo.getCustomizationUnmarshaller();

    }

}
```

with pom.xml:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.omnifaces</groupId>
    <artifactId>jaxbmr</artifactId>
    <version>1.0</version>

    <name>jaxbmr</name>
    <description>
        Test is a test for the JAX-B MR
    </description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

        <maven.compiler.source>16</maven.compiler.source>
        <maven.compiler.target>16</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.sun.xml.bind</groupId>
            <artifactId>jaxb-osgi</artifactId>
            <version>3.0.1</version>
        </dependency>
    </dependencies>
</project>
```

So I guess that's good.

Now it's a question why it doesn't work with `glassfish/appserver/tests/quicklook/wsit/JaxwsFromWsdl/build.xml` following 

```xml
 <wsimport
            debug="true"
            verbose="true"
            keep="${keep}"
            extension="${extension}"
            destdir="${build.classes.home}"
            wsdl="${basedir}/${server.wsdl}">
            <binding dir="${basedir}/etc" includes="${server.binding}"/>
        </wsimport>
```

**Comment by lukasj** [comment]
@arjantijms what does `ant -version` say?

**Comment by lukasj** [comment]
one needs a version with [the fix for 62952](https://bz.apache.org/bugzilla/show_bug.cgi?id=62952), so ant 1.10.6+, even though I'd prefer you use the latest, 1.10.9

**Comment by arjantijms** [comment]
That gives:

```
ant -v
Apache Ant(TM) version 1.10.9 compiled on September 27 2020
```

But I think it matters less, since the quicklook test is started via Maven, and therefor uses Maven's antrunner, which may use its own ant internally.

That's `glassfish/appserver/tests/quicklook/pom.xml`

```xml
 <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
		        <version>1.8</version>
                <executions>
                    <execution>
                        <id>default-test</id>
[...]
```

**Comment by arjantijms** [comment]
@lukasj That worked indeed! TIL!

Thanks a million times.
