### ISSUE TITLE
jaxb 3.0.0 xjc with class cast exception

### ISSUE THREAD

**Issue by th-developer** [eclipse-ee4j/jaxb-ri#1595]
jaxb-ri 3.0.0 latest and jaxb 3.0.0. build 178 throw class cast exception, even with samples shipped with jaxb-ri.
Tried openjdk 11.0.13 and openjdk17.0.1 in combination with ant v1.10.7 and  latest v1.10.12

```
BUILD FAILED
/opt/jaxb-ri/samples/create-marshal/build.xml:36: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.io.Closeable (jdk.internal.loader.ClassLoaders$AppClassLoader and java.io.Closeable are in module java.base of loader 'bootstrap')
        at com.sun.istack.tools.ProtectedTask.execute(ProtectedTask.java:89)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1391)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1254)
        at org.apache.tools.ant.Main.runBuild(Main.java:830)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by lukasj** [comment]
works fine in current master
