### ISSUE TITLE
Filename clash when locating resource bundle messages

### ISSUE THREAD

**Issue by dmatej** [eclipse-ee4j/jaxb-ri#1653]
In example this block in the `Messages` class results in an attempt to use directly the `Messages` class as a `ResourceBundle` which it doesn't implement. The original idea was probably to load the `Messages.properties` file in the same package. Same result is on JDK11, 17, 18.

```
    static String format( String property, Object[] args ) {
        String text = **ResourceBundle.getBundle(Messages.class.getName())**.getString(property);
        return MessageFormat.format(text,args);
    }
```

```
java.util.MissingResourceException: Can't find bundle for base name jakarta.xml.bind.Messages, locale cs_CZ
at java.base/java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
at java.base/java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
at jakarta.xml.bind.Messages.format(Messages.java:41)
at jakarta.xml.bind.Messages.format(Messages.java:22)
at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:144)
at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:340)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:349)
......
Caused by: java.lang.ClassCastException: jakarta.xml.bind.Messages cannot be cast to ResourceBundle
at java.base/java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
at java.base/java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
at java.base/java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
at java.base/java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
... 47 more
```

**Comment by dmatej** [comment]
Sorry, wrong repo.
