### ISSUE TITLE
Error while parsing rnc

### ISSUE THREAD

**Issue by asm0dey** [eclipse-ee4j/jaxb-ri#1730]
Hi everybody,

I'm trying to parse [opds.rnc](https://github.com/opds-community/specs/blob/master/schema/1.2/opds.rnc), which includes [atom.rnc](https://gist.github.com/tommorris/3725394#file-atom-rnc) with ModelLoader.load from `com.sun.xml.bind:jaxb-xjc:4.0.3`

I've got a following exception:

```
Exception in thread "main" java. lang.NullPointerException: Cannot invoke "com.sun.tools.rngom.ast.builder.CommentList.addComment(String, com.sun.tools.rngom.ast.om.Location)" because "comments" is null 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.getComments(CompactSyntax.java:330) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.noteTopLevelComments(CompactSyntax.java:294) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.NamespaceDecl(CompactSyntax.java:789) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.Preamble(CompactSyntax.java:770) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.IncludedGrammar(CompactSyntax.java:714) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.parseInclude(CompactSyntax.java:150) 
  at com.sun.tools.rngom.parse.compact.CompactParseable.parseInclude(CompactParseable.java:63) 
  at com.sun.tools.rngom.digested.IncludeImpl.endInclude(IncludeImpl.java:59) 
  at com.sun.tools.rngom.parse.host.IncludeHost.endInclude(IncludeHost.java:52) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.Include(CompactSyntax.java:1663) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.GrammarComponent(CompactSyntax.java:1563) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.GrammarBody(CompactSyntax.java:1546) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.TopLevelGrammar(CompactSyntax.java:747) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.Input(CompactSyntax.java:442) 
  at com.sun.tools.rngom.parse.compact.CompactSyntax.parse(CompactSyntax.java:135) 
  at com.sun.tools.rngom.parse.compact.CompactParseable.parse(CompactParseable.java:55)
  at com.sun.tools.xjc.ModelLoader.loadRELAXNG(ModelLoader.java:580)
  at com.sun.tools.xjc.ModelLoader.loadRELAXNGCompact(ModelLoader.java:568)
  at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:134)
  at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:88)
  at org.redundent.kotlin.xml.gen.DslGenerator.generate(DslGenerator.kt:55)
  at org.redundent.kotlin.xml.gen.DslGeneratorKt.main(DslGenerator.kt:23)
```

Indeed, sometimes the following lines:

```
          if (comments == null)
            comments = sb.makeCommentList();
```
returns the `null` comments. It seems to me that it happens when SchemaBuilder contains a `[#document: null]`.

It seems that it happens when `CompactSyntax` handles `include`. This statement is supported by the fact that when I parse just atom.rnc no errors happens.

**Comment by laurentschoelens** [comment]
Hi @asm0dey 

Since you provided the schema you try to generate java classes from, I'll try to provide a PR that fixes the error.

Regards

**Comment by asm0dey** [comment]
@laurentschoelens thank you very much! The generation of a correct code model from this schema is very interesting thing by itself because of complex hierarchies

**Comment by laurentschoelens** [comment]
By curiosity : which tool do you use to generate java classes ?

**Comment by asm0dey** [comment]
Do you mean source code? I actually generate Kotlin with KotlinPoet

**Comment by laurentschoelens** [comment]
Yes sorry, generate the source code from the rnc schema

**Comment by asm0dey** [comment]
JavaPoet and KotlinPoet are always my tools of choice for the code generation

**Comment by laurentschoelens** [comment]
Reproduced
Working on PR 😄
