### ISSUE TITLE
Issues due to #1734 #1746

### ISSUE THREAD

**Issue by laurentschoelens** [eclipse-ee4j/jaxb-ri#1756]
I've seen NPE in XJC due to #1734 (fix for #1708)
I've also seen NPE in XJC due to #1746 and errors

**Comment by laurentschoelens** [comment]
```
java.lang.NullPointerException: Cannot invoke "String.trim()" because the return value of "com.sun.tools.xjc.reader.xmlschema.bindinfo.BindInfo.getDocumentation()" is null
	at com.sun.tools.xjc.reader.xmlschema.SimpleTypeBuilder.buildCEnumConstants(SimpleTypeBuilder.java:651)
	at com.sun.tools.xjc.reader.xmlschema.SimpleTypeBuilder.bindToTypeSafeEnum(SimpleTypeBuilder.java:584)
```

```
java.lang.NullPointerException: Cannot invoke "com.sun.tools.xjc.reader.xmlschema.bindinfo.BIProperty.getOptionalPropertyMode()" because the return value of "com.sun.tools.xjc.reader.xmlschema.bindinfo.BIProperty.getDefault()" is null
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BIProperty.getOptionalPropertyMode(BIProperty.java:223)
	at com.sun.tools.xjc.reader.xmlschema.bindinfo.BIProperty.wrapUp(BIProperty.java:454)
```
