### ISSUE TITLE
ContextFactory.createContext does not support property jakarta.xml.bind.JAXBContextFactory - unable to choose JAXB reference implementation

### ISSUE THREAD

**Issue by henning-meinhardt** [eclipse-ee4j/jaxb-ri#1810]
According to JAXB 4 specification (https://github.com/jakartaee/jaxb-api/blob/master/spec/src/main/asciidoc/ch04-binding_framework.adoc) it should be possible to specify the JAXB implementation to use through a new property "jakarta.xml.bind.JAXBContextFactory" rather than using a jaxb.properties file.

While I am able to choose the EclipseLink MOXy implementation that way, I get the following error when trying to choose the Glassfish reference implementation instead (having both implementations in the classpath, e.g. "org.glassfish.jaxb:jaxb-runtime:4.0.5" and "org.eclipse.persistence:org.eclipse.persistence.moxy:4.0.4"):

```
jakarta.xml.bind.JAXBException: Eigenschaft "jakarta.xml.bind.JAXBContextFactory" wird nicht unterstützt.
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:126)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:246)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:182)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:140)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:313)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
	at org.example.Main.main(Main.java:36)
```

I'm trying to create a JAXBContext like this:
```
Map<String, String> properties = new HashMap<> ();
properties.put (JAXBContext.JAXB_CONTEXT_FACTORY, "org.glassfish.jaxb.runtime.v2.ContextFactory");
JAXBContext jc = JAXBContext.newInstance ("xxxxxxx",
	Thread.currentThread ().getContextClassLoader (), properties);
```
Setting up the property for EclipseLink MOXy instead just works fine:
```
properties.put (JAXBContext.JAXB_CONTEXT_FACTORY, "org.eclipse.persistence.jaxb.JAXBContextFactory");
```

Shouldn't the reference implementation be a good citizen and support the property as well?

**Comment by lukasj** [comment]
use [JAXBContextFactory](https://javadoc.io/doc/com.sun.xml.bind/jaxb-impl/latest/com.sun.xml.bind/org/glassfish/jaxb/runtime/v2/JAXBContextFactory.html) instead, `ContextFactory` is obsolete

**Comment by henning-meinhardt** [comment]
Hi @lukasj,

I tried that and changed my code to
```
properties.put (JAXBContext.JAXB_CONTEXT_FACTORY, "org.glassfish.jaxb.runtime.v2.JAXBContextFactory");
```
Unfortunately that does not have any effect. The exception message is still the same, just the stack traces changed and includes the JAXBContextFactory now:
```
jakarta.xml.bind.JAXBException: Eigenschaft "jakarta.xml.bind.JAXBContextFactory" wird nicht unterstützt.
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:126)
	at org.glassfish.jaxb.runtime.v2.ContextFactory.createContext(ContextFactory.java:246)
	at org.glassfish.jaxb.runtime.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:182)
	at jakarta.xml.bind.ContextFinder.newInstance(ContextFinder.java:140)
	at jakarta.xml.bind.ContextFinder.find(ContextFinder.java:313)
	at jakarta.xml.bind.JAXBContext.newInstance(JAXBContext.java:392)
	at org.example.Main.main(Main.java:39)
```
