### ISSUE TITLE
Nullpointer Exception in DTD parsing

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jaxb-ri#574]
Using the xjc tool contained in JDK 1.6.0_10 do this:

xjc -dtd WebDAV.dtd

with the following WebDAV.dtd file:

```
<!ELEMENT activelock (lockscope, locktype, depth, owner?, timeout?, locktoken?,
lockroot) >
<!ELEMENT allprop EMPTY >
<!ELEMENT collection EMPTY >
<!ELEMENT depth (#PCDATA) >
<!ELEMENT error ANY >
<!ELEMENT exclusive EMPTY >
<!ELEMENT href (#PCDATA) >
<!ELEMENT include ANY >
<!ELEMENT location (href) >
<!ELEMENT lockentry (lockscope, locktype) >
<!ELEMENT lockinfo (lockscope, locktype, owner?) >
<!ELEMENT lockroot (href) >
<!ELEMENT lockscope (exclusive | shared) >
<!ELEMENT locktoken (href) >
<!ELEMENT locktype (write) >
<!ELEMENT multistatus (response*, responsedescription?) >
<!ELEMENT owner ANY >
<!ELEMENT prop ANY >
<!ELEMENT propertyupdate (remove | set)+ >
<!ELEMENT propfind ( propname | (allprop, include?) | prop ) >
<!ELEMENT propname EMPTY >
<!ELEMENT propstat (prop, status, error?, responsedescription?) >
<!ELEMENT remove (prop) >
<!ELEMENT response (href, ((href*, status)|(propstat+)), error?,
responsedescription? , location?) >
<!ELEMENT responsedescription (#PCDATA) >
<!ELEMENT set (prop) >
<!ELEMENT shared EMPTY >
<!ELEMENT status (#PCDATA) >
<!ELEMENT timeout (#PCDATA) >
<!ELEMENT wite EMPTY >
```

and you will get this:

parsing a schema...
compiling a schema...
Exception in thread "main" java.lang.NullPointerException
at com.sun.tools.xjc.generator.bean.field.AbstractField$1TypeList.add(Ab
stractField.java:427)
at com.sun.tools.xjc.generator.bean.field.AbstractField$1TypeList.add(Ab
stractField.java:439)
at com.sun.tools.xjc.generator.bean.field.AbstractField.getType(Abstract
Field.java:443)
at com.sun.tools.xjc.generator.bean.field.AbstractField.<init>(AbstractF
ield.java:117)
at com.sun.tools.xjc.generator.bean.field.AbstractListField.<init>(Abstr
actListField.java:105)
at com.sun.tools.xjc.generator.bean.field.UntypedListField.<init>(Untype
dListField.java:105)
at com.sun.tools.xjc.generator.bean.field.UntypedListFieldRenderer.gener
ate(UntypedListFieldRenderer.java:58)
at com.sun.tools.xjc.generator.bean.field.DefaultFieldRenderer.generate(
DefaultFieldRenderer.java:75)
at com.sun.tools.xjc.generator.bean.BeanGenerator.generateFieldDecl(Bean
Generator.java:744)
at com.sun.tools.xjc.generator.bean.BeanGenerator.generateClassBody(Bean
Generator.java:532)
at com.sun.tools.xjc.generator.bean.BeanGenerator.<init>(BeanGenerator.j
ava:234)
at com.sun.tools.xjc.generator.bean.BeanGenerator.generate(BeanGenerator
.java:174)
at com.sun.tools.xjc.model.Model.generateCode(Model.java:286)
at com.sun.tools.xjc.Driver.run(Driver.java:339)
at com.sun.tools.xjc.Driver.run(Driver.java:190)
at com.sun.tools.xjc.Driver._main(Driver.java:115)
at com.sun.tools.xjc.Driver.access$000(Driver.java:73)
at com.sun.tools.xjc.Driver$1.run(Driver.java:95)

The strange thing is that when you move this line:

<!ELEMENT responsedescription (#PCDATA) >

from WebDAV.dtd into another DTD file, and then run xjc first on WebDAV.dtd and
then on the other DTD file, both files will run perfectly and you will have the
expected result (which is an acceptable workaround, but totally strange).
#### Environment
Operating System: All
Platform: All
#### Affected Versions
[2.1]

**Comment by antoniosanct** [comment]
Maybe #1702 fixes this issue.

Regards,
Antonio.

**Comment by lukasj** [comment]
works for me now in master
